const Media = [
    [
        require("./Sudaka/Sudaka_1.jpg"),
        require("./Sudaka/Sudaka_2.jpg"),
        require("./Sudaka/Sudaka_3.jpg"),
        require("./Sudaka/Sudaka_4.jpg"),
        require("./Sudaka/Sudaka_5.jpg"),
        require("./Sudaka/Sudaka_6.jpg")
    ],
    [
        require("./AlgoDeCarlos/AlgoDeCarlos_1.jpg"),
        require("./AlgoDeCarlos/AlgoDeCarlos_2.jpg"),
        require("./AlgoDeCarlos/AlgoDeCarlos_3.jpg"),
        require("./AlgoDeCarlos/AlgoDeCarlos_4.jpg"),
        require("./AlgoDeCarlos/AlgoDeCarlos_5.jpg")
    ],
    [
        require("./WarholRMX/WarholRMX_1.jpg"),
        require("./WarholRMX/WarholRMX_2.jpg"),
        require("./WarholRMX/WarholRMX_3.jpg"),
        require("./WarholRMX/WarholRMX_4.jpg"),
        require("./WarholRMX/WarholRMX_5.jpg"),
        require("./WarholRMX/WarholRMX_6.jpg")
    ],
    [
        require("./Almamora/Almamora_1.jpg"),
        require("./Almamora/Almamora_2.jpg"),
        require("./Almamora/Almamora_3.jpg")
    ],
    [
        require("./Levis/Levis_1.jpg"),
        require("./Levis/Levis_2.jpg"),
        require("./Levis/Levis_3.jpg"),
        require("./Levis/Levis_4.jpg"),
        require("./Levis/Levis_5.jpg"),
        require("./Levis/Levis_6.jpg"),
        require("./Levis/Levis_7.jpg"),
        require("./Levis/Levis_8.jpg")
    ],
    [
        require("./Muta/Muta_5.png"),
        require("./Muta/Muta_1.png"),
        require("./Muta/Muta_2.png"),
        require("./Muta/Muta_3.png"),
        require("./Muta/Muta_4.png")
    ],
    [
        require("./Nosotras/Nosotras_1.jpg"),
        require("./Nosotras/Nosotras_2.jpg"),
        require("./Nosotras/Nosotras_3.jpg"),
        require("./Nosotras/Nosotras_4.jpg"),
        require("./Nosotras/Nosotras_5.jpg")
    ],
    [
        require("./Quilmes/QuilmesIPA_1.jpg"),
        require("./Quilmes/QuilmesIPA_2.jpg"),
        require("./Quilmes/QuilmesIPA_3.jpg"),
        require("./Quilmes/QuilmesIPA_4.jpg"),
        require("./Quilmes/QuilmesIPA_5.jpg")
    ]
];

export default Media;